project_id = "mgknzbjzwtkumdihzthd"

[functions.create-user]
verify_jwt = false

[functions.notify-supplier]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.resolve-google-maps-url]
verify_jwt = false

[functions.generate-access-link]
verify_jwt = false

[functions.validate-access-token]
verify_jwt = false

[functions.revoke-access-token]
verify_jwt = false

[functions.backfill-pdv-managers]
verify_jwt = false

[functions.optimize-route]
verify_jwt = false
